apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test-php-web
  labels:
    app: nginx
    role: leader
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        role: leader
        tier: frontend
    spec:
      containers:
      - name: myweb
        image: bitnami/nginx:latest