apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: test-php-web
  labels:
    app: php
    role: leader
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
        role: leader
        tier: frontend
    spec:
      containers:
      - name: phpfpm
        tty: true # Enables debugging capabilities when attached to this container.
        image: bitnami/php-fpm:latest
        ports:
          - containerPort: 9000