apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-php-web-deployment
  namespace: test-php-web
  labels:
    app: test-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
      - name: php-nginx
        image: gbxnga/laravel-aws-eks:v2
        ports:
        - containerPort: 80 
        env:
        - name: DB_HOST
          value: localhost
        - name: DB_DATABASE
          value: test_db
        - name: DB_USERNAME
          value: ifew 
        - name: DB_PASSWORD
          value: password1234
      - name: mysql
        image: mysql:5 
        env:
        - name: MYSQL_DATABASE
          value: test_db
        - name: MYSQL_USER
          value: ifew
        - name: MYSQL_PASSWORD
          value: password1234 
        - name: MYSQL_ROOT_PASSWORD
          value: password1234root