apiVersion: v1
kind: Service
metadata:
  name: mydb-service
  namespace: myweb
  labels:
    app: mydb
spec:
  selector:
    app: mydb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer